### ISSUE TITLE
Management API loses the channels at shutdown of queue master

### ISSUE THREAD

**Issue by abra7134** [rabbitmq/rabbitmq-server#1087]
In the beginning we will start two instances cluster of RabbitMQ v3.6.6, like as in [official documentation](http://www.rabbitmq.com/clustering.html#single-machine):

```
$ RABBITMQ_NODE_PORT=5672 RABBITMQ_SERVER_START_ARGS="-rabbitmq_management listener [{port,15672}]" RABBITMQ_NODENAME=p5672 rabbitmq-server -detached
Warning: PID file not written; -detached was passed.
$ RABBITMQ_NODE_PORT=5673 RABBITMQ_SERVER_START_ARGS="-rabbitmq_management listener [{port,15673}]" RABBITMQ_NODENAME=p5673 rabbitmq-server -detached
Warning: PID file not written; -detached was passed.
$ rabbitmqctl -n p5673 stop_app
Stopping node p5673@mq ...
$ rabbitmqctl -n p5673 join_cluster p5672@`hostname -s`
Clustering node p5673@mq with p5672@mq ...
$ rabbitmqctl -n p5673 start_app
Starting node p5673@mq ...
```

And set high availability (mirroring) for queues:
```
$ rabbitmqctl -n p5672 set_policy ha-all "" '{"ha-mode":"all", "ha-sync-mode":"automatic"}'
Setting policy "ha-all" for pattern [] to "{\"ha-mode\":\"all\", \"ha-sync-mode\":\"automatic\"}" with priority "0" ...
```

Next we create new queue and send the message, as in official [tutorial ](http://www.rabbitmq.com/tutorials/tutorial-two-python.html) there:

```python
#!/usr/bin/env python
import pika
import sys

connection = pika.BlockingConnection(pika.ConnectionParameters(
      host='localhost', port=5672))
channel = connection.channel()

channel.queue_declare(queue='task_queue', durable=True)

message = ' '.join(sys.argv[1:]) or "Hello World!"
channel.basic_publish(exchange='',
                      routing_key='task_queue',
                      body=message,
                      properties=pika.BasicProperties(
                         delivery_mode = 2, # make message persistent
                      ))
print(" [x] Sent %r" % message)
connection.close()
```

And we are convinced that the script has created queue and its master is p5672:

```
$ curl -u guest:guest http://localhost:15673/api/queues?columns=name,node,slave_nodes
[{"slave_nodes":["p5673@mq"],"node":"p5672@mq","name":"task_queue"}]
```

Next we start working process for obtaining the messages from **slave** node at a background:

```python
#!/usr/bin/env python
import pika
import time

connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost', port=5673))
channel = connection.channel()

channel.queue_declare(queue='task_queue', durable=True)
print(' [*] Waiting for messages. To exit press CTRL+C')

def callback(ch, method, properties, body):
    print(" [x] Received %r" % body)
    time.sleep(body.count(b'.'))
    print(" [x] Done")
    ch.basic_ack(delivery_tag = method.delivery_tag)

channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback,
                      queue='task_queue')

channel.start_consuming()
```

And we are convinced that the script created connection and the channel by means of management API and rabbitmqctl:

```
$ rabbitmqctl -n p5673 list_connections
Listing connections ...
guest   ::1     34492   running
$ rabbitmqctl -n p5673 list_channels
Listing channels ...
<p5673@mq.2.1500.0>     guest   1       0
$ curl -u guest:guest http://localhost:15673/api/connections?columns=name
[{"name":"[::1]:34492 -> [::1]:5673"}]
$ curl -u guest:guest http://localhost:15673/api/channels?columns=name
[{"name":"[::1]:34492 -> [::1]:5673 (1)"}]
```

Next we stop p5672 node (master of queue):

```
$ rabbitmqctl -n p5672 stop_app                        
Stopping node p5672@mq ...
```

And we watch everything again:

```
$ curl -u guest:guest http://localhost:15673/api/queues?columns=name,node,slave_nodes
[{"slave_nodes":[],"node":"p5673@mq","name":"task_queue"}]
$ rabbitmqctl -n p5673 list_connections
Listing connections ...
guest   ::1     34492   running
$ rabbitmqctl -n p5673 list_channels
Listing channels ...
<p5673@mq.2.1500.0>     guest   1       0
$ curl -u guest:guest http://localhost:15673/api/connections?columns=name
[{"name":"[::1]:34492 -> [::1]:5673"}]
$ curl -u guest:guest http://localhost:15673/api/channels?columns=name
[]
```

As we see the channel was gone from management API though is registered in rabbitmq and at the same time everything works further, i.e. messages are normally published and caught by a worker on the same connection.

**Comment by michaelklishin** [comment]
Sorry but we no longer investigate issue with the pre-#236 stats collector.

**Comment by michaelklishin** [comment]
You can try to reproduce this with 3.6.7 Milestone 3.

**Comment by abra7134** [comment]
I have install v3.6.6.903 on Debian v8.7 from .deb, and began to repeat everything on steps.
After sending the message to queue (the first python script), in the server log the following mistakes appear:
```
=ERROR REPORT==== 24-Jan-2017::11:22:19 ===
** Generic server <0.697.0> terminating
** Last message in was {'$gen_cast',
                           {method,
                               {'basic.publish',0,<<>>,<<"task_queue">>,
                                   false,false},
                               {content,60,none,
                                   <<16,0,2>>,
                                   rabbit_framing_amqp_0_9_1,
                                   [<<"Hello World!">>]},
                               flow}}
** When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,<0.687.0>,
                            <0.695.0>,<0.687.0>,
                            <<"[::1]:33499 -> [::1]:5672">>,
                            {lstate,<0.696.0>,false},
                            none,1,
                            {[],[]},
                            {user,<<"guest">>,
                                [administrator],
                                [{rabbit_auth_backend_internal,none}]},
                            <<"/">>,<<"task_queue">>,
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {state,
                                {dict,0,16,16,8,80,48,
                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]},
                                    {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]}}},
                                erlang},
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {set,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            <0.690.0>,
                            {state,fine,5000,#Ref<0.0.0.4565>},
                            false,1,
                            {{0,nil},{0,nil}},
                            [],
                            {{0,nil},{0,nil}},
                            [{<<"connection.blocked">>,bool,true},
                             {<<"authentication_failure_close">>,bool,true},
                             {<<"consumer_cancel_notify">>,bool,true},
                             {<<"publisher_confirms">>,bool,true},
                             {<<"basic.nack">>,bool,true}],
                            none,0,none,flow,[]}
** Reason for termination == 
** {{cannot_compile_forms,error},
    [{code_version,compile_forms,1,[{file,"src/code_version.erl"},{line,97}]},
     {code_version,update,1,[{file,"src/code_version.erl"},{line,63}]},
     {rabbit_core_metrics,ets_update_counter,4,
                          [{file,"src/rabbit_core_metrics.erl"},{line,183}]},
     {rabbit_core_metrics,channel_stats,4,
                          [{file,"src/rabbit_core_metrics.erl"},{line,149}]},
     {rabbit_channel,'-incr_stats/2-lc$^0/1-0-',2,
                     [{file,"src/rabbit_channel.erl"},{line,2002}]},
     {rabbit_channel,deliver_to_queues,2,
                     [{file,"src/rabbit_channel.erl"},{line,1860}]},
     {rabbit_channel,handle_method,3,
                     [{file,"src/rabbit_channel.erl"},{line,958}]},
     {rabbit_channel,handle_cast,2,
                     [{file,"src/rabbit_channel.erl"},{line,459}]}]}

=ERROR REPORT==== 24-Jan-2017::11:22:19 ===
Error on AMQP connection <0.687.0> ([::1]:33499 -> [::1]:5672, vhost: '/', user: 'guest', state: closing), channel 1:
{{cannot_compile_forms,error},
 [{code_version,compile_forms,1,[{file,"src/code_version.erl"},{line,97}]},
  {code_version,update,1,[{file,"src/code_version.erl"},{line,63}]},
  {rabbit_core_metrics,ets_update_counter,4,
                       [{file,"src/rabbit_core_metrics.erl"},{line,183}]},
  {rabbit_core_metrics,channel_stats,4,
                       [{file,"src/rabbit_core_metrics.erl"},{line,149}]},
  {rabbit_channel,'-incr_stats/2-lc$^0/1-0-',2,
                  [{file,"src/rabbit_channel.erl"},{line,2002}]},
  {rabbit_channel,deliver_to_queues,2,
                  [{file,"src/rabbit_channel.erl"},{line,1860}]},
  {rabbit_channel,handle_method,3,
                  [{file,"src/rabbit_channel.erl"},{line,958}]},
  {rabbit_channel,handle_cast,2,
                  [{file,"src/rabbit_channel.erl"},{line,459}]}]}

=WARNING REPORT==== 24-Jan-2017::11:22:19 ===
Non-AMQP exit reason '{{cannot_compile_forms,error},
                       [{code_version,compile_forms,1,
                            [{file,"src/code_version.erl"},{line,97}]},
                        {code_version,update,1,
                            [{file,"src/code_version.erl"},{line,63}]},
                        {rabbit_core_metrics,ets_update_counter,4,
                            [{file,"src/rabbit_core_metrics.erl"},{line,183}]},
                        {rabbit_core_metrics,channel_stats,4,
                            [{file,"src/rabbit_core_metrics.erl"},{line,149}]},
                        {rabbit_channel,'-incr_stats/2-lc$^0/1-0-',2,
                            [{file,"src/rabbit_channel.erl"},{line,2002}]},
                        {rabbit_channel,deliver_to_queues,2,
                            [{file,"src/rabbit_channel.erl"},{line,1860}]},
                        {rabbit_channel,handle_method,3,
                            [{file,"src/rabbit_channel.erl"},{line,958}]},
                        {rabbit_channel,handle_cast,2,
                            [{file,"src/rabbit_channel.erl"},{line,459}]}]}'

=INFO REPORT==== 24-Jan-2017::11:22:19 ===
closing AMQP connection <0.687.0> ([::1]:33499 -> [::1]:5672)
```

And worker process (the second python script) take off with a error:
```
$ ./worker.py
 [*] Waiting for messages. To exit press CTRL+C
 [x] Received 'Hello World!'
 [x] Done
Traceback (most recent call last):
  File "./worker.py", line 21, in <module>
    channel.start_consuming()
  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 955, in start_consuming
    self.connection.process_data_events()
  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 243, in process_data_events
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
```

And server log:
```
=INFO REPORT==== 24-Jan-2017::11:32:45 ===
accepting AMQP connection <0.1427.0> ([::1]:34661 -> [::1]:5673)

=ERROR REPORT==== 24-Jan-2017::11:32:45 ===
** Generic server <0.1435.0> terminating
** Last message in was {'$gen_cast',
                        {deliver,
                         <<"ctag1.7b0c1c033977462d86b2e76df6a1f505">>,true,
                         {{resource,<<"/">>,queue,<<"task_queue">>},
                          <30777.700.0>,0,true,
                          {basic_message,
                           {resource,<<"/">>,exchange,<<>>},
                           [<<"task_queue">>],
                           {content,60,
                            {'P_basic',undefined,undefined,undefined,2,
                             undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined,undefined,
                             undefined,undefined},
                            <<16,0,2>>,
                            rabbit_framing_amqp_0_9_1,
                            [<<"Hello World!">>]},
                           <<129,105,138,93,63,115,23,109,185,102,170,115,223,
                             188,88,161>>,
                           true}}}}
** When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,<0.1427.0>,
                         <0.1433.0>,<0.1427.0>,
                         <<"[::1]:34661 -> [::1]:5673">>,
                         {lstate,<0.1434.0>,false},
                         none,1,
                         {[],[]},
                         {user,<<"guest">>,
                          [administrator],
                          [{rabbit_auth_backend_internal,none}]},
                         <<"/">>,<<"task_queue">>,
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                            [[<30777.700.0>|
                              {resource,<<"/">>,queue,<<"task_queue">>}]],
                            []}}},
                         {state,
                          {dict,1,16,16,8,80,48,
                           {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                           {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                             [[<30777.700.0>|#Ref<0.0.0.20659>]],
                             []}}},
                          erlang},
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],
                            [[<<"ctag1.7b0c1c033977462d86b2e76df6a1f505">>|
                              {{amqqueue,
                                {resource,<<"/">>,queue,<<"task_queue">>},
                                true,false,none,[],<30777.700.0>,
                                [<0.1216.0>],
                                [<0.1216.0>],
                                [p5673@mq],
                                [{vhost,<<"/">>},
                                 {name,<<"ha-all">>},
                                 {pattern,<<>>},
                                 {'apply-to',<<"all">>},
                                 {definition,
                                  [{<<"ha-mode">>,<<"all">>},
                                   {<<"ha-sync-mode">>,<<"automatic">>}]},
                                 {priority,0}],
                                [{<0.1217.0>,<0.1216.0>},
                                 {<30777.703.0>,<30777.700.0>}],
                                [],live,0},
                               {false,1,false,[]}}]],
                            [],[],[],[],[],[]}}},
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                            [[<30777.700.0>|
                              {1,
                               {<<"ctag1.7b0c1c033977462d86b2e76df6a1f505">>,
                                nil,nil}}]],
                            []}}},
                         {set,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                            [<30777.700.0>],
                            []}}},
                         <0.1428.0>,
                         {state,fine,5000,#Ref<0.0.0.20652>},
                         false,1,
                         {{0,nil},{0,nil}},
                         [],
                         {{0,nil},{0,nil}},
                         [{<<"connection.blocked">>,bool,true},
                          {<<"authentication_failure_close">>,bool,true},
                          {<<"consumer_cancel_notify">>,bool,true},
                          {<<"publisher_confirms">>,bool,true},
                          {<<"basic.nack">>,bool,true}],
                         none,1,none,flow,[]}
** Reason for termination == 
** {bad_return_value,{cannot_compile_forms,error}}

=ERROR REPORT==== 24-Jan-2017::11:32:45 ===
Error on AMQP connection <0.1427.0> ([::1]:34661 -> [::1]:5673, vhost: '/', user: 'guest', state: running), channel 1:
{bad_return_value,{cannot_compile_forms,error}}

=WARNING REPORT==== 24-Jan-2017::11:32:45 ===
Non-AMQP exit reason '{bad_return_value,{cannot_compile_forms,error}}'

=INFO REPORT==== 24-Jan-2017::11:32:45 ===
closing AMQP connection <0.1427.0> ([::1]:34661 -> [::1]:5673)
```

**Comment by michaelklishin** [comment]
@abra7134 this is something entirely unrelated. Please take this to rabbitmq-users. I suspect that some Erlang/OTP modules are not available on your system: please mention what version is used and how it was provisioned on the list.

**Comment by abra7134** [comment]
Ok, I have published in [rabbitmq-management](https://github.com/rabbitmq/rabbitmq-management) repo.

**Comment by kjnilsson** [comment]
I have tested this and can reproduce the issue against 3.6.6 but _not_ against 3.6.7 (with the new management plugin).
