### ISSUE TITLE
3.13.2: "x-opt-rabbitmq-received-time" only available for new messages

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#11300]
## Discussed in https://github.com/rabbitmq/rabbitmq-server/discussions/11262

Originally posted by @gblessas, May 17, 2024

### Describe the bug

Context: where messages are published from MQTT to a topic exchange with `timestamp_in_ms` enabled with 3.12.x version of rabbit. Messages are stored in a stream bound to the topic.

* Before upgrading to `3.13.2`:
  * Messages in the stream can be read via AMQP 0.9.1 (pika) and contain the `timestamp_in_ms` field.
  * Messages in the stream consumed via the stream protocol do not have this field available.

* After upgrading to `3.13.2`:
  * Messages in the stream can be read via AMQP 0.9.1 (pika) and contain the `timestamp_in_ms` field. 
  * Messages in the stream can be consumed via the stream protocol (rstream) but `timestamp_in_ms` is not available via the `x-opt-rabbitmq-received-time` annotation.
  * New messages published via MQTT then consumed via the stream protocol (rstream) _DO_ contain the annotation `x-opt-rabbitmq-received-time`.
  * _ALL_ messages, when read via AMQP 0.9.1, will contain `timestamp_in_ms`, which is odd, since only _NEW_ messages will have it when read via the stream protocol.

### Reproduction steps

Please see this repository:
https://github.com/lukebakken/rabbitmq-server-11262?tab=readme-ov-file#reproduction

### Expected behavior

after upgrade timestamp_in_ms field should be available in stream protocol for already existing messages through x-opt-rabbitmq-received-time. not only for new messages.

### Additional context

Code to reproduce the issue:
https://github.com/lukebakken/rabbitmq-server-11262

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/pull/10925 is highly relevant.

**Comment by ansd** [comment]
I'm unable to follow the 1st command in https://github.com/lukebakken/rabbitmq-server-11262?tab=readme-ov-file#setup:
on both OSX and Ubuntu.
On OSX:
```
pipenv install
[pipenv.exceptions.InstallError]:       uamqp/c_uamqp.c:112651:55: error: no member named 'ob_digit' in 'struct _longobject'
[pipenv.exceptions.InstallError]:                   const digit* digits = ((PyLongObject*)x)->ob_digit;
[pipenv.exceptions.InstallError]:                                         ~~~~~~~~~~~~~~~~~~  ^
[pipenv.exceptions.InstallError]:       fatal error: too many errors emitted, stopping now [-ferror-limit=]
[pipenv.exceptions.InstallError]:       294 warnings and 20 errors generated.
[pipenv.exceptions.InstallError]:       error: command '/usr/bin/clang' failed with exit code 1
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for uamqp
[pipenv.exceptions.InstallError]: ERROR: Could not build wheels for uamqp, which is required to install pyproject.toml-based projects
ERROR: Couldn't install package: {}
 Package installation failed...
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py:1127: ResourceWarning: subprocess 96436 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

On Ubuntu:
```
An error occurred while installing urllib3==2.2.1; python_version >= '3.8' --hash=sha256:450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d --hash=sha256:d0570876c61ab9e520d776c38acbbb5b05a776d3f9ff98a5c8fd5162a444cf19! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: ERROR: Exception:00
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
[pipenv.exceptions.InstallError]:     status = run_func(*args)
[pipenv.exceptions.InstallError]:              ^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
[pipenv.exceptions.InstallError]:     return func(self, options, args)
[pipenv.exceptions.InstallError]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 315, in run
[pipenv.exceptions.InstallError]:     session = self.get_default_session(options)
[pipenv.exceptions.InstallError]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
[pipenv.exceptions.InstallError]:     self._session = self.enter_context(self._build_session(options))
[pipenv.exceptions.InstallError]:                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
[pipenv.exceptions.InstallError]:     session = PipSession(
[pipenv.exceptions.InstallError]:               ^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
[pipenv.exceptions.InstallError]:     self.headers["User-Agent"] = user_agent()
[pipenv.exceptions.InstallError]:                                  ^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
[pipenv.exceptions.InstallError]:     setuptools_dist = get_default_environment().get_distribution("setuptools")
[pipenv.exceptions.InstallError]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 180, in get_distribution
[pipenv.exceptions.InstallError]:     return next(matches, None)
[pipenv.exceptions.InstallError]:            ^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 175, in <genexpr>
[pipenv.exceptions.InstallError]:     matches = (
[pipenv.exceptions.InstallError]:               ^
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 594, in iter_all_distributions
[pipenv.exceptions.InstallError]:     for dist in self._iter_distributions():
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 168, in _iter_distributions
[pipenv.exceptions.InstallError]:     for dist in finder.find_eggs(location):
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 136, in find_eggs
[pipenv.exceptions.InstallError]:     yield from self._find_eggs_in_dir(location)
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 103, in _find_eggs_in_dir
[pipenv.exceptions.InstallError]:     from pip._vendor.pkg_resources import find_distributions
[pipenv.exceptions.InstallError]:   File "/home/david/.local/share/virtualenvs/rabbitmq-server-11262-zVGl6YQ3/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
[pipenv.exceptions.InstallError]:     register_finder(pkgutil.ImpImporter, find_on_path)
[pipenv.exceptions.InstallError]:                     ^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]: AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
ERROR: Couldn't install package: certifi
 Package installation failed...
```

However, I can confirm without following the reproduction steps that the following expected behaviour is wrong:
> Expected behavior
after upgrade timestamp_in_ms field should be available in stream protocol for already existing messages through x-opt-rabbitmq-received-time. not only for new messages.

This is because a message that got written into the Stream in 3.12 won't contain message annotation `x-opt-rabbitmq-received-time` because this annotation is available for messages that are written into the Stream after 3.13.2 thanks to https://github.com/rabbitmq/rabbitmq-server/pull/10925 .

**Comment by gblessas** [comment]
Why do you asked me all the code to reproduce if you clearly consider it is a "normal" behaviour.

**Comment by lukebakken** [comment]
> Why do you asked me all the code to reproduce if you clearly consider it is a "normal" behaviour

Because we weren't 100% sure what you were actually doing, and thought you may have found a bug. At least, I thought so, but my colleague disagreed.

Personally, I appreciate the time you took to provide very clear instructions and code to reproduce what you are doing. I wish every RabbitMQ user did that when they filed an issue report, but very few actually do.

**Comment by gblessas** [comment]
A shame there is no Way to update existing queues . New serveurs Will have 3.13 so they can use stream. My last concern is that if the "annotation" can be present in stream and amqp field too, it means to me that the information is store and distributed twice for each message ? Am i right ?
