### ISSUE TITLE
CLI: error message when running cli tools without sudo.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1296]
After installation of `3.7.0-milestone.16` on debian, run `rabbitmqctl` as non-root user:
```
rabbitmqctl
** (throw) {:error, {:cannot_read_enabled_plugins_file, '/etc/rabbitmq/enabled_plugins', :eacces}}
    (rabbit) src/rabbit_plugins.erl:184: :rabbit_plugins.read_enabled/1
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:66: RabbitMQ.CLI.Core.CommandModules.plugin_modules/1
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:55: RabbitMQ.CLI.Core.CommandModules.load_commands/2
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:40: RabbitMQ.CLI.Core.CommandModules.load/1
    (rabbitmqctl) lib/rabbitmq/cli/ctl/commands/help_command.ex:137: RabbitMQ.CLI.Ctl.Commands.HelpCommand.commands/0
    (rabbitmqctl) lib/rabbitmq/cli/ctl/commands/help_command.ex:65: RabbitMQ.CLI.Ctl.Commands.HelpCommand.all_usage/1
    (rabbitmqctl) lib/rabbitmqctl.ex:57: RabbitMQCtl.exec_command/2
    (rabbitmqctl) lib/rabbitmqctl.ex:43: RabbitMQCtl.main/1

```

Previous versions were printing a message that `rabbitmqctl` should be run as root.

**Comment by hairyhum** [comment]
When pressing TAB to autocomplete a command, the same error occurs. Probably because autocompletion runs without `sudo`. Maybe we should make sure `rabbitmqctl` does not fail with this error unless access to the `enabled_plugins` file is required.

**Comment by michaelklishin** [comment]
Good idea.
