### ISSUE TITLE
listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_protocol:start_link/4 at <0.18023.990> exit with reason

### ISSUE THREAD

**Issue by liwenxian** [rabbitmq/rabbitmq-server#1391]
server  info:
RabbitMQ 3.6.11, Erlang 19.0.4

sharerabbitmq-01   log

sharerabbitmq-01.log:=ERROR REPORT==== 11-Oct-2017::21:42:29 ===
sharerabbitmq-01.log-Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_protocol:start_link/4 at <0.18023.990> exit with reason: [{reason,{timeout,{gen_se
rver,call,[<0.1102.0>,{fetch,#Fun<rabbit_mgmt_db.22.104142656>,[[[{name,<<"biz_parent_queue_add_article">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,false},{owner_pid,non
e},{arguments,{struct,[]}},{pid,<8721.488.0>},{state,live}],[{name,<<"biz_parent_queue_add_article_monitor">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,false},{owner_pid,
none},{arguments,{struct,[]}},{pid,<8721.700.0>},{state,live}],[{name,<<"biz_parent_queue_add_article_sandbox">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,false},{owner_p
id,none},{arguments,{struct,[]}},{pid,<8721.718.0>},{state,live}],[{name,<<"biz_parent_queue_add_article_score">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,false},{owner_
pid,none},{arguments,{struct,[]}},{pid,<8721.526.0>},{state,live}],[{name,<<"biz_parent_queue_add_article_timeline">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,false},{ow
ner_pid,none},{arguments,{struct,[]}},{pid,<8721.632.0>},{state,live}],[{name,<<"biz_parent_queue_add_article_timeline_sandbox">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusiv
e,false},{owner_pid,none},{arguments,{struct,[]}},{pid,<8721.508.0>},{state,live}],[{name,<<"biz_parent_queue_add_comment">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,fal
se},{owner_pid,none},{arguments,{struct,[]}},{pid,<8721.653.0>},{state,live}],[{name,<<"biz_parent_queue_add_comment_sandbox">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive,
false},{owner_pid,none},{arguments,{struct,[]}},{pid,<8721.513.0>},{state,live}],[{name,<<"biz_parent_queue_add_comment_score">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclusive
,false},{owner_pid,none},{arguments,{struct,[]}},{pid,<8721.683.0>},{state,live}],[{name,<<"biz_parent_queue_add_comment_timeline">>},{vhost,<<"/">>},{durable,true},{auto_delete,false},{exclu……

sharerabbitmq-02   log
=WARNING REPORT==== 11-Oct-2017::21:41:51 ===
closing AMQP connection <0.16665.444> (10.80.123.123:38823 -> 10.80.122.123:5672, vhost: '/', user: 'quanzi'):
client unexpectedly closed TCP connection

=ERROR REPORT==== 11-Oct-2017::21:43:31 ===
closing AMQP connection <0.6434.207> (10.47.123.123:27873 -> 10.80.122.123:5672):
missed heartbeats from client, timeout: 30s

=WARNING REPORT==== 11-Oct-2017::21:48:21 ===
closing AMQP connection <0.17488.444> (10.80.123.123:37700 -> 10.80.122.123:5672, vhost: '/', user: 'quanzi'):
client unexpectedly closed TCP connection

client log

2017-10-11 21:41:48.109 [AMQP Connection 10.80.122.123:5672] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler(124) - An unexpected connection driver error occured
com.rabbitmq.client.MissedHeartbeatException: Heartbeat missing with heartbeat = 30 seconds
        at com.rabbitmq.client.impl.AMQConnection.handleSocketTimeout(AMQConnection.java:730) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:649) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:579) [amqp-client-4.1.0.jar:4.1.0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

2017-10-11 21:43:04.450 [AMQP Connection 10.80.122.123:5672] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler(124) - Caught an exception during connection recovery!
java.util.concurrent.TimeoutException
        at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:398) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:304) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62) ~[amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:531) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:494) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:700) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:694) [amqp-client-4.1.0.jar:4.1.0]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:584) [amqp-client-4.1.0.jar:4.1.0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by michaelklishin** [comment]
Timeouts is a fact of life in a production system under load, as are missed [heartbeats](http://www.rabbitmq.com/heartbeats.html).
