### ISSUE TITLE
The queue does not respond to any operation.

### ISSUE THREAD

**Issue by zcgewu** [rabbitmq/rabbitmq-server#1749]
### **Asking for information on management page**
![image](https://user-images.githubusercontent.com/6211911/47548165-b139a900-d92a-11e8-8a92-db6afbaf21cd.png)

`2018-10-26 14:13:40.368 [error] <0.27215.7438> Channel error on connection <0.28852.7438> (<rabbit@sz-rabbitmq-prd-10-10-xx-xx.1.28852.7438>, vhost: '/', user: 'guest'), channel 1:
operation basic.get caused a channel exception not_found: failed to perform operation on queue 'order.union.returns.queue' in vhost '/' due to timeout`

### **Queue information**
![image](https://user-images.githubusercontent.com/6211911/47548576-19d55580-d92c-11e8-9be7-b8bb160e71ac.png)

### **Nodes information**
![image](https://user-images.githubusercontent.com/6211911/47548675-44271300-d92c-11e8-92ab-9df8689fb34d.png)

**Comment by zcgewu** [comment]
### Java client connects queue error stack

`2018-09-30 15:50:43,126 WARN  Consumer raised exception, processing can restart if the connection factory supports it
org.springframework.amqp.AmqpIOException: java.io.IOException
 at org.springframework.amqp.rabbit.connection.RabbitUtils.convertRabbitAccessException(RabbitUtils.java:112)
 at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:106)
 at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:605)
 at org.springframework.amqp.rabbit.core.RabbitAdmin.initialize(RabbitAdmin.java:309)
 at org.springframework.amqp.rabbit.core.RabbitAdmin$10.onCreate(RabbitAdmin.java:243)
 at org.springframework.amqp.rabbit.connection.CompositeConnectionListener.onCreate(CompositeConnectionListener.java:31)
 at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:230)
 at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:119)
 at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:163)
 at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:109)
 at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:199)
 at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:524)
 at java.lang.Thread.run(Thread.java:662)
Caused by: java.io.IOException
 at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
 at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
 at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124)
 at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:733)
 at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:61)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:348)
 at $Proxy150.queueDeclare(Unknown Source)
 at org.springframework.amqp.rabbit.core.RabbitAdmin.declareQueues(RabbitAdmin.java:342)
 at org.springframework.amqp.rabbit.core.RabbitAdmin.access$200(RabbitAdmin.java:46)
 at org.springframework.amqp.rabbit.core.RabbitAdmin$11.doInRabbit(RabbitAdmin.java:312)
 at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:600)
 ... 10 more
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; reason: {#method<channel.close>(reply-code=404, reply-text=NOT_FOUND - failed to perform operation on queue 'order.union.returns.queue' in vhost '/' due to timeout, class-id=50, method-id=10), null, ""}
 at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
 at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
 at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:343)
 at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:216)
 at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
 ... 22 more`

**Comment by zcgewu** [comment]
用这个试试，强制删除僵死队列
`rabbitmqctl eval '{ok, Q} = rabbit_amqqueue:lookup(rabbit_misc:r(<<"vhost名">>, queue,<<"队列名">>)), rabbit_amqqueue:delete_crashed(Q).'`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
