### ISSUE TITLE
Test `tests_0-8.queue.QueueTests.test_purge` fails to pass

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#225]
When running `make full` in rabbitmq-test with the `master` branch, the testsuite fails:
```
tests_0-8.queue.QueueTests.test_purge .................................................................................................................................................................................................................................... fail
Error during test:
  Traceback (most recent call last):
    File "qpid_testsuite/qpid-python-test", line 307, in run
      phase()
    File "/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/rabbitmq-test/qpid_testsuite/tests_0-8/queue.py", line 70, in test_purge
      self.assertChannelException(404, e.args[0])
    File "/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/rabbitmq-test/qpid_testsuite/qpid/testlib.py", line 155, in assertChannelException
      if not isinstance(message, Message): self.fail("expected channel_close method, got %s" % (message))
    File "/usr/local/lib/python2.7/unittest/case.py", line 412, in fail
      raise self.failureException(msg)
  AssertionError: expected channel_close method, got worker closed
```

In the `-sasl.log` file, we get:
```
=CRASH REPORT==== 21-Jul-2015::11:12:37 ===
  crasher:
    initial call: gen:init_it/6
    pid: <0.677.0>
    registered_name: []
    exception exit: {amqp_error,not_found,"no previously declared queue",none}
      in function  gen_server2:terminate/3 (src/gen_server2.erl, line 1146)
    ancestors: [<0.674.0>,<0.659.0>,<0.652.0>,<0.651.0>,
                  rabbit_tcp_client_sup,rabbit_sup,<0.394.0>]
    messages: []
    links: [<0.674.0>]
    dictionary: [{process_name,
                      {rabbit_channel,
                          {<<"127.0.0.1:51066 -> 127.0.0.1:5672">>,3}}}]
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 1224
  neighbours:

...

=CRASH REPORT==== 21-Jul-2015::11:12:37 ===
  crasher:
    initial call: rabbit_reader:init/2
    pid: <0.653.0>
    registered_name: []
    exception error: no match of right hand side value 
                     {3,
                      {'channel.close',404,
                          <<"NOT_FOUND - no previously declared queue">>,0,0}}
      in function  rabbit_reader:handle_exception/3 (src/rabbit_reader.erl, line 773)
      in call from rabbit_reader:handle_dependent_exit/3 (src/rabbit_reader.erl, line 696)
      in call from rabbit_reader:mainloop/4 (src/rabbit_reader.erl, line 486)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 415)
      in call from rabbit_reader:start_connection/5 (src/rabbit_reader.erl, line 376)
    ancestors: [<0.651.0>,rabbit_tcp_client_sup,rabbit_sup,<0.394.0>]
    messages: [{'EXIT',#Port<0.6170>,normal}]
    links: [<0.651.0>]
    dictionary: [{process_name,
                      {rabbit_reader,<<"127.0.0.1:51066 -> 127.0.0.1:5672">>}},
                  {{ch_pid,<0.663.0>},{1,#Ref<0.0.3.1626>}},
                  {{ch_pid,<0.673.0>},{2,#Ref<0.0.3.1681>}},
                  {{channel,1},{<0.663.0>,{method,rabbit_framing_amqp_0_9_1}}},
                  {credit_blocked,[]},
                  {{credit_from,<0.663.0>},196},
                  {credit_flow_default_credit,{200,50}},
                  {{channel,2},
                   {<0.673.0>,{method,rabbit_framing_amqp_0_9_1}}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7338
  neighbours:
```

Jenkins first reported the failure at 2015-07-20 17:17:17 CEST. This is may be related to the merge of rabbitmq/rabbitmq-server#214.

**Comment by videlalvaro** [comment]
Fixed in https://github.com/rabbitmq/rabbitmq-server/commit/4352e0c23fdc7ae87c8eb5e63204f29746bf64c1
