### ISSUE TITLE
rabbitmq management api timeout issue

### ISSUE THREAD

**Issue by ssk199441** [rabbitmq/rabbitmq-server#5748]
I am using Rabbitmq version (3.8.14), and using it as 8 node cluster using kubenetes.
In my prod environment , i have nearly
connections 25000
queues  29000
exchanges 56000
consumer 50000
channels 25000
and also lot user,permissions, bindings

I am taking backup using the management API `curl -k -u  username:password https://localhost:9450/api/definitions ` but it get timed out after one minute and my code clearly indicates it timed out at rabbitmq

My application is ssl enabled(HTTPS) , when i used that option my pod not coming up, is there any other option that i need to give o configure this.

How to avoid time out after one , when taking backup using management API, also i posed question rabbitmq google groups but i did't get enough answers
https://groups.google.com/g/rabbitmq-users/c/2dibT7etGC4/m/u4NpVEb5AQAJ?utm_medium=email&utm_source=footer

I have referred to following page increased the timedout
https://www.rabbitmq.com/management.html

# For RabbitMQ 3.7.9 and later versions.
#
# Configures HTTP (non-encrypted) listener timeouts
management.tcp.idle_timeout       = 120000
management.tcp.inactivity_timeout = 120000
management.tcp.request_timeout    = 10000

# For RabbitMQ 3.7.9 and later versions.
#
# Configures HTTPS (TLS-enabled) listener timeouts
management.ssl.idle_timeout       = 120000
management.ssl.inactivity_timeout = 120000
management.ssl.request_timeout    = 10000

**Comment by ssk199441** [comment]
Error log:

Error logs:

Traceback (most recent call last):
  File "backup.py", line 15, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "backup.py", line 11, in main
    async with session.get(pokemon_url,  ssl=False) as resp:
  File "/home/ironfist/python-rmq_backup/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/ironfist/python-rmq_backup/venv/lib/python3.8/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/home/ironfist/python-rmq_backup/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/ironfist/python-rmq_backup/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
