### ISSUE TITLE
RabbitMQ Streams protocol: server should respond with an error when client attempts to publish zero messages

### ISSUE THREAD

**Issue by wrobell** [rabbitmq/rabbitmq-server#6166]
When I send empty publish request to RabbitMQ Streams broker, then I receive no response.

By empty request, I mean: key, version, publisher id and **zero** length array as published messages.

Obviously, this is an error on my library side causing my applications to hang forever waiting for a response. Therefore I fixed it on my side.

However, IMHO, it would be good if RabbitMQ responded with publish error in such situation. I believe, this would improve robustness of the whole system.

**Comment by lukebakken** [comment]
> By empty request, I mean: key, version, publisher id and zero length array as published messages.

Just so we see _exactly_ the same issue you do, if you could provide code that I can clone, compile and run to see the same behavior that would help facilitate a fix. Thanks.

**Comment by acogoluegnes** [comment]
The publish command is asynchronous, so the best I can think of is to send an empty [`PublishError`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_stream/docs/PROTOCOL.adoc#publisherror).

> Obviously, this is an error on my library side causing my applications to hang forever waiting for a response.
This should not happen though, no outbound messages means no outstanding confirms, so the library should not be affected.

**Comment by wrobell** [comment]
You can replicate the issue with the following steps

1. Install RbFly version 0.5.0 (later versions have a fix in the library itself: `pip install rbfly==0.5.0`.
2. Create `test-perf-stream` RabbitMQ stream.
3. Start wireshark (see below for the command).
4. Run the `send-6166` script (see below for the script): `python send-6166 rabbitmq-stream://guest:guest@localhost test-perf-stream`

The `send-6166` script
```
import argparse
import asyncio
import logging

import rbfly.streams as rbs

@rbs.connection
async def send_data(client: rbs.StreamsClient, stream: str) -> None:
    print('before: send to rabbitmq server')
    async with client.publisher(stream, cls=rbs.PublisherBatch) as publisher:
        await publisher.flush()
    print('after: send to rabbitmq server')

parser = argparse.ArgumentParser()
parser.add_argument(
    '--verbose', action='store_true',
    help='explain what is being done'
)
parser.add_argument('uri', help='RabbitMQ Streams broker URI')
parser.add_argument('stream', help='Stream name')

args = parser.parse_args()

level = logging.DEBUG if args.verbose else logging.INFO
logging.basicConfig(level=level)

client = rbs.streams_client(args.uri)

task = send_data(client, args.stream)
asyncio.run(task)
```

The output of the script is (please note that "after: send to rabbitmq server" is missing, the script hangs at `publisher.flush()`)
```
$ python send-6166 rabbitmq-stream://guest:guest@localhost test-perf-stream
before: send to rabbitmq server
INFO:rbfly.cm:connecting...
INFO:rbfly.streams.client:rabbitmq streams protocol created: rabbitmq-stream://guest@localhost:5552//
INFO:rbfly.streams.protocol:tune frame sent, frame size=1048576, heartbeat=60
INFO:rbfly.streams.protocol:connection handshake performed
INFO:rbfly.streams.client:rabbitmq streams client connected: rabbitmq-stream://guest@localhost:5552//
INFO:rbfly.streams.client:publisher (re)created, name=greymatter/6310, stream=test-perf-stream, message id=0
^CINFO:rbfly.streams.protocol:connection is closed
INFO:rbfly.streams.client:rabbitmq streams client disconnected: rabbitmq-stream://guest@localhost:5552//
Traceback (most recent call last):
  File "/home/wrobell/projects/rbfly/issue-6166/send-6166", line 32, in <module>
    asyncio.run(task)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1863, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

The wireshark command, its output and my commentary
```
$ tshark -f 'tcp port 5552' -i lo -E header=yes -E separator=, -E quote=d -T fields -e frame.time -e tcp.port -e data

### connect to rabbitmq stream, and declare publisher for a stream
"Oct 28, 2022 18:59:49.618400549 IST","37464,5552",
"Oct 28, 2022 18:59:49.618410741 IST","5552,37464",
"Oct 28, 2022 18:59:49.618419491 IST","37464,5552",
"Oct 28, 2022 18:59:49.646381014 IST","37464,5552","000000c2"
"Oct 28, 2022 18:59:49.646391745 IST","5552,37464",
"Oct 28, 2022 18:59:49.646400968 IST","37464,5552","001100010000000100000004000770726f6475637400055262466c790008706c6174666f726d0006507974686f6e0009636f70797269676874001e436f70797269676874202843292041727475722057726f626c6577736b69000b696e666f726d6174696f6e005a4c6963656e73656420756e64657220474e55205075626c6963204c6963656e73652076657273696f6e2033206f72206c617465722c207365652068747470733a2f2f6769746c61622e636f6d2f77726f62656c6c2f7262666c79"
"Oct 28, 2022 18:59:49.646403246 IST","5552,37464",
"Oct 28, 2022 18:59:49.649169902 IST","5552,37464","000001068011000100000001000100000006000c636c75737465725f6e616d65001b677265796d617474657240677265796d61747465722e7768616c650009636f707972696768740037436f707972696768742028632920323030372d3230323220564d776172652c20496e632e206f722069747320616666696c69617465732e000b696e666f726d6174696f6e00394c6963656e73656420756e64657220746865204d504c20322e302e20576562736974653a2068747470733a2f2f7261626269746d712e636f6d0008706c6174666f726d001145726c616e672f4f54502032352e312e31000770726f6475637400085261626269744d51000776657273696f6e0006332e31312e32"
"Oct 28, 2022 18:59:49.649187981 IST","37464,5552",
"Oct 28, 2022 18:59:49.649483664 IST","37464,5552","00000008"
"Oct 28, 2022 18:59:49.649493906 IST","37464,5552","0012000100000002"
"Oct 28, 2022 18:59:49.649554309 IST","5552,37464",
"Oct 28, 2022 18:59:49.649623729 IST","5552,37464","0000001f80120001000000020001000000020008414d51504c41494e0005504c41494e"
"Oct 28, 2022 18:59:49.649705662 IST","37464,5552","0000001f"
"Oct 28, 2022 18:59:49.649712627 IST","37464,5552","00130001000000030005504c41494e0000000c006775657374006775657374"
"Oct 28, 2022 18:59:49.649833870 IST","5552,37464",
"Oct 28, 2022 18:59:49.649963183 IST","5552,37464","0000000a80130001000000030001"
"Oct 28, 2022 18:59:49.649980949 IST","5552,37464","0000000c00140001001000000000003c"
"Oct 28, 2022 18:59:49.650004115 IST","37464,5552",
"Oct 28, 2022 18:59:49.677341335 IST","37464,5552","0000000c"
"Oct 28, 2022 18:59:49.677357399 IST","37464,5552","00140001001000000000003c"
"Oct 28, 2022 18:59:49.677506678 IST","5552,37464",
"Oct 28, 2022 18:59:49.677571926 IST","37464,5552","0000000b"
"Oct 28, 2022 18:59:49.677578230 IST","37464,5552","001500010000000400012f"
"Oct 28, 2022 18:59:49.677666217 IST","5552,37464",
"Oct 28, 2022 18:59:49.677752789 IST","5552,37464","000000428015000100000004000100000002000f616476657274697365645f706f7274000435353532000f616476657274697365645f686f7374000a677265796d6174746572"
"Oct 28, 2022 18:59:49.678028426 IST","37464,5552","0000002c"
"Oct 28, 2022 18:59:49.678035761 IST","37464,5552","000100010000000501000f677265796d61747465722f363331300010746573742d706572662d73747265616d"
"Oct 28, 2022 18:59:49.678062997 IST","5552,37464",
"Oct 28, 2022 18:59:49.678146876 IST","5552,37464","0000000a80010001000000050001"
"Oct 28, 2022 18:59:49.678212788 IST","37464,5552","0000002b"
"Oct 28, 2022 18:59:49.678218466 IST","37464,5552","0005000100000006000f677265796d61747465722f363331300010746573742d706572662d73747265616d"
"Oct 28, 2022 18:59:49.678235873 IST","5552,37464",
"Oct 28, 2022 18:59:49.678315137 IST","5552,37464","00000012800500010000000600010000000000000000"

### send publish command to a stream with zero messages
"Oct 28, 2022 18:59:49.678473632 IST","37464,5552","00000009"
"Oct 28, 2022 18:59:49.678479976 IST","37464,5552","000200010100000000"
"Oct 28, 2022 18:59:49.678498384 IST","5552,37464",

#
# no response from rabbitmq server for about 3 seconds
# it would be great to get a publish error here
#

### script send-6166 is terminated with C-c by me
"Oct 28, 2022 18:59:52.851733498 IST","37464,5552","00000009"
"Oct 28, 2022 18:59:52.851775347 IST","37464,5552","000600010000000701"
"Oct 28, 2022 18:59:52.851846859 IST","5552,37464",
"Oct 28, 2022 18:59:52.851971246 IST","5552,37464","0000000a80060001000000070001"
"Oct 28, 2022 18:59:52.852183695 IST","37464,5552","0000000e"
"Oct 28, 2022 18:59:52.852203941 IST","37464,5552","0016000100000008000100024f4b"
"Oct 28, 2022 18:59:52.852234588 IST","5552,37464",
"Oct 28, 2022 18:59:52.852281596 IST","5552,37464","0000000a80160001000000080001"
"Oct 28, 2022 18:59:52.852324084 IST","5552,37464",
"Oct 28, 2022 18:59:52.853151278 IST","37464,5552",
"Oct 28, 2022 18:59:52.853178771 IST","5552,37464",
```
