### ISSUE TITLE
Definition export fails with a JSON encoding exception on nodes with previously stored definition import hash

### ISSUE THREAD

**Issue by gcolombeau** [rabbitmq/rabbitmq-server#6424]
Info:
* RabbitMQ 3.11.3
* Erlang 25.1.2 [jit]

Activating the `skip_if_unchanged` configuration when loading definitions files at boot time breaks the export definitions functionality. The definitions are correctly imported but exporting through the CLI ends up in the following error:
```
bash-5.1# rabbitmqctl export_definitions -
Stack trace: 

** (FunctionClauseError) no function clause matching in JSON.Encoder.BitString.encode_binary_recursive/2
    lib/json/encoder/default_implementations.ex:92: JSON.Encoder.BitString.encode_binary_recursive(<<141, 84, 42, 105, 244, 199, 109, 169, 137, 84, 114, 185, 111, 86, 82, 86, 195, 39, 193, 131, 215, 106, 234, 210, 101, 198, 97, 47, 209, 132, 188>>, 'I')
    lib/json/encoder/default_implementations.ex:90: JSON.Encoder.BitString.encode/1
    lib/json/encoder/helpers.ex:28: JSON.Encoder.Helpers.encode_item/1
    lib/json/encoder/helpers.ex:23: anonymous fn/1 in JSON.Encoder.Helpers.dict_encode/1
    (elixir 1.14.0) lib/enum.ex:1755: anonymous fn/2 in Enum.map_join/3
    (elixir 1.14.0) lib/enum.ex:1725: anonymous fn/4 in Enum.map_intersperse/3
    (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
    (elixir 1.14.0) lib/enum.ex:2480: Enum.map_intersperse/3

Error:
:function_clause
```

Exporting through the management overview page ends up in the following logs:
```
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>   crasher:
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     initial call: cowboy_stream_h:request_process/3
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     pid: <0.917.0>
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     registered_name: []
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     exception error: {invalid_byte,<<"0x8D">>,
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>                                    <<73,141,84,42,105,244,199,109,169,137,84,
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>                                      114,185,111,86,82,86,195,39,193,131,215,
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>                                      106,234,210,101,198,97,47,209,132,188>>}
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in function  thoas_encode:escape_json_chunk/5 (src/thoas_encode.erl, line 1716)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:encode_string/2 (src/thoas_encode.erl, line 106)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:map_naive_loop/2 (src/thoas_encode.erl, line 1712)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:map_naive/2 (src/thoas_encode.erl, line 1704)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:list/2 (src/thoas_encode.erl, line 1692)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:map_naive_loop/2 (src/thoas_encode.erl, line 1712)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:map_naive_loop/2 (src/thoas_encode.erl, line 1713)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>       in call from thoas_encode:map_naive/2 (src/thoas_encode.erl, line 1704)
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     ancestors: [<0.861.0>,<0.753.0>,<0.751.0>,<0.750.0>,<0.748.0>,
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>                   rabbit_web_dispatch_sup,<0.737.0>]
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     message_queue_len: 0
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     messages: []
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     links: [<0.861.0>]
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     dictionary: []
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     trap_exit: false
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     status: running
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     heap_size: 4185
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     stack_size: 28
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>     reductions: 4419
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0>   neighbours:
2022-11-17 13:24:42.649199+00:00 [error] <0.917.0> 
2022-11-17 13:24:42.649916+00:00 [error] <0.861.0> Ranch listener {acceptor,{0,0,0,0,0,0,0,0},15672}, connection process <0.861.0>, stream 39 had its request process <0.917.0> exit with reason {invalid_byte,<<"0x8D">>,<<73,141,84,42,105,244,199,109,169,137,84,114,185,111,86,82,86,195,39,193,131,215,106,234,210,101,198,97,47,209,132,188>>} and stacktrace [{thoas_encode,escape_json_chunk,5,[{file,"src/thoas_encode.erl"},{line,1716}]},{thoas_encode,encode_string,2,[{file,"src/thoas_encode.erl"},{line,106}]},{thoas_encode,map_naive_loop,2,[{file,"src/thoas_encode.erl"},{line,1712}]},{thoas_encode,map_naive,2,[{file,"src/thoas_encode.erl"},{line,1704}]},{thoas_encode,list,2,[{file,"src/thoas_encode.erl"},{line,1692}]},{thoas_encode,map_naive_loop,2,[{file,"src/thoas_encode.erl"},{line,1712}]},{thoas_encode,map_naive_loop,2,[{file,"src/thoas_encode.erl"},{line,1713}]},{thoas_encode,map_naive,2,[{file,"src/thoas_encode.erl"},{line,1704}]}]
2022-11-17 13:24:42.649916+00:00 [error] <0.861.0> 
```

I'm seeing this behavior on the Docker image `rabbitmq:3.11.3-management-alpine` (Erlang 25.1.2) with the following configuration:
```ini
# When set to true, definition import will only happen
# if definition file contents change
definitions.skip_if_unchanged = true

definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.d/
```

This behavior is reproducible at least on the non-alpine version and RabbitMQ version 3.11.2 and when specifying a single file instead of a directory.

Everything works as expected when switching the configuration to:
```ini
load_definitions = /etc/rabbitmq/definitions.d/
```

**Comment by michaelklishin** [comment]
Also, what happens if you try to export definitions in the Erlang term format? See `--format` in `rabbitmqctl help export_definitions`.

**Comment by michaelklishin** [comment]
Looking at various issues mentioning `0x8D` I come to the conclusion that the contents of the definition map is incompatible (encoding-wise) with the exact way we encode it to JSON.

`skip_if_unchanged` likely has nothing to do with it, unless the problematic part of the map is the runtime parameter that it sets with the latest computed definition file hash.

**Comment by gcolombeau** [comment]
I was pretty sure at the beginning my file was at fault but at the end this is the behavior I experience. Exporting in the Erlang format seems to work.

Here is a minimum definition file that reproduces the behavior on my end, it only creates the `guest` user:
```json
{
	"bindings": [],
	"exchanges": [],
	"global_parameters": [],
	"parameters": [],
	"permissions": [],
	"policies": [],
	"queues": [],
	"rabbit_version": "3.11.3",
	"rabbitmq_version": "3.11.3",
	"topic_permissions": [],
	"users": [
		{
			"hashing_algorithm": "rabbit_password_hashing_sha256",
			"limits": {},
			"name": "guest",
			"password_hash": "wO4btAPK/oS/ihaiBlpmg2ZkbCYc2LFc1ivBR3szzSjk6R1v",
			"tags": [
				"administrator"
			]
		}
	],
	"vhosts": []
}
```

**Comment by lukebakken** [comment]
What do you know, I can reproduce this using 3.11.3 on Windows. Investigating.

**Comment by lukebakken** [comment]
It's the imported defs hash value:

```
% 09:46:43 <0.1179.0>(dead)
% thoas_encode:escape_json(<<"imported_definition_hash_value">>, <<"imported_definition_hash_value">>, 0)
                       
% 09:46:43 <0.1179.0>(dead)
% thoas_encode:escape_json(<<"imported_definition_hash_value">>, [], <<"imported_definition_hash_value">>, 0)
                       
% 09:46:43 <0.1179.0>(dead)
% thoas_encode:escape_json(<<"value">>, <<"value">>, 0)
                       
% 09:46:43 <0.1179.0>(dead)
% thoas_encode:escape_json(<<"value">>, [], <<"value">>, 0)
                       
% 09:46:43 <0.1179.0>(dead)
% thoas_encode:escape_json(<<131,9,87,73,57,61,3,232,16,150,176,178,119,99,119,161,217,136,231,214,93,111,
  224,168,246,189,231,104,200,100,166,93>>, <<131,9,87,73,57,61,3,232,16,150,176,178,119,99,119,161,217,136,231,214,93,111,
  224,168,246,189,231,104,200,100,166,93>>, 0)
                       
% 09:46:43 <0.1179.0>(dead)
% thoas_encode:escape_json(<<131,9,87,73,57,61,3,232,16,150,176,178,119,99,119,161,217,136,231,214,93,111,
  224,168,246,189,231,104,200,100,166,93>>, [], <<131,9,87,73,57,61,3,232,16,150,176,178,119,99,119,161,217,136,231,214,93,111,
  224,168,246,189,231,104,200,100,166,93>>, 0)
```
