### ISSUE TITLE
rabbitmqctl: Error creating virtualhosts using quorum queues as default queue type

### ISSUE THREAD

**Issue by asaldalop** [rabbitmq/rabbitmq-server#7750]
### Describe the bug

When trying to create virtualhosts using the `rabbitmqctl` cli with the argument `--default-queue-type quorum`, it is throwing the following error:

```
Stack trace:

** (UndefinedFunctionError) function FeatureFlags.assert_feature_flag_enabled/3 is undefined (module FeatureFlags is not available)
    FeatureFlags.assert_feature_flag_enabled(:"rabbit@host1", :quorum_queue, #Function<1.125780349/0 in RabbitMQ.CLI.Ctl.Commands.AddVhostCommand.run/2>)
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:166: RabbitMQCtl.maybe_run_command/3
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:134: anonymous fn/5 in RabbitMQCtl.do_exec_parsed_command/5
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:616: RabbitMQCtl.maybe_with_distribution/3
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:99: RabbitMQCtl.exec_command/2
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:33: RabbitMQCtl.main/1
    (elixir 1.13.4) lib/kernel/cli.ex:126: anonymous fn/3 in Kernel.CLI.exec_fun/2

Error:
:undef
```

It looks that this bug was introduced in version 3.11.10 because has been verified in prior versions and the virtualhost is created successfully.

### Reproduction steps

1. Install RabbitMQ 3.11.10 or 3.11.11 on Linux
2. Run the following command:
`rabbitmqctl add_vhost "test" --default-queue-type quorum`
3. The console output shows the following error:
```
Stack trace:

** (UndefinedFunctionError) function FeatureFlags.assert_feature_flag_enabled/3 is undefined (module FeatureFlags is not available)
    FeatureFlags.assert_feature_flag_enabled(:"rabbit@host1", :quorum_queue, #Function<1.125780349/0 in RabbitMQ.CLI.Ctl.Commands.AddVhostCommand.run/2>)
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:166: RabbitMQCtl.maybe_run_command/3
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:134: anonymous fn/5 in RabbitMQCtl.do_exec_parsed_command/5
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:616: RabbitMQCtl.maybe_with_distribution/3
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:99: RabbitMQCtl.exec_command/2
    (rabbitmqctl 3.11.0) lib/rabbitmqctl.ex:33: RabbitMQCtl.main/1
    (elixir 1.13.4) lib/kernel/cli.ex:126: anonymous fn/3 in Kernel.CLI.exec_fun/2

Error:
:undef
```
4. No virtualhost is created

### Expected behavior

`rabbitmqctl add_vhost "test" --default-queue-type quorum` shouldn't throw any error in the console and the virtualhost, with quorum queues as default queue type, should be created in the RabbitMQ cluster.

**Comment by michaelklishin** [comment]
This issue is not present in `main` but I could reproduce with `3.11.11`.

**Comment by michaelklishin** [comment]
This is due to a missing import. It was deleted in https://github.com/rabbitmq/rabbitmq-server/pull/7435 (possibly because it is not present in `main` because QQ is a mandatory feature flag there).
