### ISSUE TITLE
Build Failure with Elixir 1.15

### ISSUE THREAD

**Issue by VlkrS** [rabbitmq/rabbitmq-server#8702]
### Describe the bug

I encounter a build failure in rabbitmq_cli when attempting to build from source with GNU Make and Elixir 1.15:

```
make[3]: Leaving directory '/build/pobj/rabbitmq-3.11.19/rabbitmq-server-3.11.19/deps/observer_cli'
Compiling 230 files (.ex)

== Compilation error in file lib/rabbit_common/records.ex ==
** (ArgumentError) lib file rabbit_common/include/rabbit.hrl could not be found
    (elixir 1.15.0) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir 1.15.0) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir 1.15.0) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/rabbit_common/records.ex:14: (module)
gmake[2]: *** [Makefile:104: escript/rabbitmqctl] Error 1
gmake[2]: Leaving directory '/build/pobj/rabbitmq-3.11.19/rabbitmq-server-3.11.19/deps/rabbitmq_cli'
gmake[1]: *** [../../erlang.mk:4512: deps] Error 2
gmake[1]: Leaving directory '/build/pobj/rabbitmq-3.11.19/rabbitmq-server-3.11.19/deps/rabbit'
gmake: *** [erlang.mk:4512: deps] Error 2
```

### Reproduction steps

1. unpack source tarball
2. remove calls to mix format, to avoid the build breaking due to changes in mix.format:
```diff
--- deps/rabbitmq_cli/mix.exs.orig
+++ deps/rabbitmq_cli/mix.exs
@@ -203,21 +203,18 @@ defmodule RabbitMQCtl.MixfileBase do
         "deps.compile"
       ],
       make_app: [
-        "format --check-formatted",
         "compile",
         "escript.build"
       ],
       make_all: [
         "deps.get",
         "deps.compile",
-        "format --check-formatted",
         "compile",
         "escript.build"
       ],
       make_all_in_src_archive: [
         "deps.get --only prod",
         "deps.compile",
-        "format --check-formatted",
         "compile",
         "escript.build"
       ]
```
4. ```make all manpages```
5. build fails, see above

### Expected behavior

The build should work, since Elixir 1.15 is whitelisted :-D

### Additional context

I *assume* that this is due to Elixir 1.15's code path pruning, see "Potential Incompatibilities" [here](https://github.com/elixir-lang/elixir/releases/tag/v1.15.0)

**Comment by michaelklishin** [comment]
It's being worked on, the issue is. It really on the RabbitMQ side but we understand how both 1.14 and 1.15 can be supported.
