### ISSUE TITLE
When using rabbitmq for batch consumption, consumption failure will be sent to errorChannel, and you will encounter an error that List<Message> cannot be forced to Message

### ISSUE THREAD

**Issue by duanmourena** [rabbitmq/rabbitmq-server#9230]
### Describe the bug

When using rabbitmq for batch consumption, the consumption failure will be sent to errorChannel, and you will encounter an error that List<Message> cannot be forced to Message. The code location is as follows. When registering ErrorMessageHandler, it will be called
`Message amqpMessage = StaticMessageHeaderAccessor.getSourceData(message);`

The messages in batch consumption are List<Message>, which cannot be received by Message

### Reproduction steps

1. @Bean
	Consumer<List<Thing>> input()
2.An exception is thrown in the consumption logic
3.View log error
...

### Expected behavior

The exception log is as follows

`Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.springframework.amqp.core.Message
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder$3.handleMessage(RabbitMessageChannelBinder.java:879) ~[spring-cloud-stream-binder-rabbit-3.2.7.jar:3.2.7]
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:222) ~[spring-integration-core-5.5.17.jar:5.5.17]
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:178) ~[spring-integration-core-5.5.17.jar:5.5.17]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.17.jar:5.5.17]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.17.jar:5.5.17]
	... 24 common frames omitted`

**Comment by duanmourena** [comment]
source location
`org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder#getErrorMessageHandler`
