### ISSUE TITLE
Incorrect credentials result in the socket just being closed

### ISSUE THREAD

**Issue by edmorley** [rabbitmq/rabbitmq-server#947]
I originally filed this against Kombu (celery/kombu#611), however it appears that the issue is with rabbitmq-server itself.

**STR:**
1) `sudo apt-get install rabbitmq-server` on Ubuntu 16.04 using the rabbitmq.com APT repository (which at time of filing results in rabbitmq-server v3.6.5-1)
2) `pip install kombu==3.0.35 amqp==1.4.9 anyjson==0.3.3`
3) Run this (using Python 2.7.12):
```python
#!/usr/bin/env python

from kombu import Connection

connection = Connection('amqp://guest:invalid_password@localhost:5672')
connection.connect()
print("connection.connected: %s" % connection.connected)
```

**Expected:**
Some distinct response from the server that make it clear that the connection was refused due to invalid username/password, that the client is then able to handle appropriately.

**Actual:**
The server just closes the connection, like so...

```
Traceback (most recent call last):
  File "./kombu-test.py", line 6, in <module>
    connection.connect()
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/home/vagrant/.virtualenvs/kombu/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
socket.error: [Errno 104] Connection reset by peer
```

In other environments I've also seen `IOError: Socket closed` ([example](https://bugzilla.mozilla.org/show_bug.cgi?id=1281810#c0)) - I'm guessing the difference is that SSL was enabled there.

This is really frustrating, since the connection error sounds like there was a network issue rather than incorrect credentials -- there have now been at least three occasions in the last 9 months where my team have been trying to debug issues, only to have it turn out to be due to someone rotating credentials (or changing permissions) they shouldn't have (yeah I know...!).

Thanks :-)

**Comment by michaelklishin** [comment]
Available [as of RabbitMQ 3.2.0](http://www.rabbitmq.com/auth-notification.html) as a protocol extension (the spec dictates that the server must close the socket without sending any more data).

**Comment by edmorley** [comment]
Could we revisit that spec design choice?

It may also be good to mention that auth failures are expected to result in the socket being closed on http://www.rabbitmq.com/authentication.html - and link to the auth-notification plugin page from there.

**Comment by michaelklishin** [comment]
@edmorley please take a look at the doc page. We *have* revisited this design choice for clients that opt-in. That is not a plugin. The page describes how it works and what clients need to do to get a notification before the socket is closed.

**Comment by edmorley** [comment]
Ah I see!

In many other places "extensions" are used as a synonym for "add-ons" or "plugins", so on reading http://www.rabbitmq.com/auth-notification.html I'd interpreted the parent category name "Our Extensions" to mean "Official plugins" rather than "Additional features compared to the AMQP spec".

**Comment by michaelklishin** [comment]
I updated 2 out of 3 authentication related guides to link to each other and added a section on authentication failures per your suggestion. Thank you! The updates are already live.

**Comment by edmorley** [comment]
That's perfect - thank you for your help! :-)
